team-apm/apm-data

- data/plugins_list.xml
Add all plugins from amate and aoytsk to the xml.
The following python script will convert the xml file into one that can be read by the current version of apm. Verify the text and installation behavior by loading the converted file into apm.
``` python
import xml.etree.ElementTree as ET
path = ['plugins_list.xml', 'scripts_list.xml']
for p in path:
tree = ET.parse('data/' + p)
root = tree.getroot()
for file in root.findall('.//file'):
file.attrib.pop("archivePath", None)
tree.write('out/' + p, encoding='UTF-8')
```
> feat: add amate, aoytsk plugins

- data/packages_list.xml
This commit fixes the problem that "apm" cannot install "DirectShow File Reader プラグイン for AviUtl"
Related to hal-shu-sato/apm#99
> fix: set archivePath to dsinput

- data/packages_list.xml
This commit fixes the problem that all scripts are uninstalled on uninstalling "拡張編集RAMプレビュー".
> fix: fix the problem that all scripts are uninstalled on uninstalling "拡張編集RAMプレビュー"

- data/core.xml
- data/packages_list.xml
- schema/packages_list.xsd
The xml structure has been updated. The lua51jit.dll has been optionalized, but is still installed correctly on 0.93rc1.
Fixes #1 .
Load the file with apm and verify the displayed text.
> feat: update the xml structure

- data/packages_list.xml
Add all plugins from oov to the xml. I haven't added "かんしくん" because it is not a plugin by itself, but it is included in PSDToolKit.
> feat: add oov packages

- data/mod.xml
- data/packages_list.xml
Fix a problem that uninstalling x264guiEx/x265guiEx affects other packages.
Tested by uninstalling x264guiEx/x265guiEx after installing QSVEnc.
> fix: fix a problem that uninstalling x264guiEx/x265guiEx affects other packages

- data/core.xml
- data/mod.xml
- schema/au.xsd
Use hashes to estimate the version of a manually installed program. This should not be a breaking change and needs to be tested with the current version of apm.
You can install aviutl and exedit with this xml loaded in the current version of apm.
> feat: add hash to the versions

- v2/data/mod.xml
- v2/data/packages.xml
Prevent the bulk install function from freezing by removing packages whose certificates have been revoked.
- closes https://github.com/hal-shu-sato/apm/issues/343
- Batch installation was performed with apm v2.0.0.
> fix: remove a batch installation package

- README.en.md
- README.md
- v2/data/mod.xml
- v2/data/packages.xml
- v2/schema/au.xsd
A fix to the patch.aul installation path, with the addition of an obsolete flag.
- https://github.com/hal-shu-sato/apm/pull/399
- Do not merge this PR until [#399](https://github.com/hal-shu-sato/apm/pull/399) is released.
- closes https://github.com/hal-shu-sato/apm-data/issues/123
> fix: fix to patch.aul installation path

- v2/data/core.xml
- v2/data/mod.xml
- v2/data/packages.xml
Strict v2 data for automatic generation of v3 data. Currently `files` in the `release` tag are not read by apm and are safe to delete.
> refactor: make some XML files strict

- v2/data/mod.xml
- v2/data/packages.xml
- Change the download URL of the patch.aul.
- Update version to the latest version.
apm v2.1.1 could install it correctly.
> fix: change the download URL of patch.aul

- v3/list.json
- v3/packages.json
- update archivePath of suzune/WideDialog
- team-apm/apm#765
> fix: update the archivePath of suzune/WideDialog

- .github/workflows/check-update.yml
- util/lib/unzip.js
Fix a problem that integrity with Japanese file name is not generated when a package is automatically updated.
I have done a test run of Github Actions in my repository.
> fix: specify shift_jis when linux

- v3/list.json
- v3/packages.json
- v3/scripts.json
Make #274, a PR created by @shumm7 for data v2, compatible with data v3.
- closes #274
- Othello and MineSweeper work properly.
> fix2: remove dot_drawer.lua and shu_game.lua

- .github/workflows/check-update.yml
- v3/list.json
- v3/packages.json
Fix problem with apm's "recommended install" feature breaking every time MrOjii/LSMASHWorks is updated.
I am intentionally specifying the old `rev1101` zip file to test the proper execution of Action.
- The commands has been tested on linux, not on Github Action.
> feat: directURL with build number

- .github/workflows/check-update.yml
Fixes a bug introduced by #464 that caused updates to fail. URL of the zip file is now escaped before being passed to `sed`.
-Action working properly (#472).
> fix: fix check-update.yml

- .github/workflows/check-update.yml
- util/check-update.js
- util/lib/unzip.js
Currently, automatic updating of apm-data has stopped.
This PR allows workflow to run in a Windows environment similar to that of apm, preventing character code-related bugs that can cause stops.
I have confirmed that `check-update` works correctly in my repository.
> feat: run the update in Windows

- v3/packages.json
Fix a bug that caused the configuration file, `SplitWindow.xml`, to be overwritten on update.
`SplitWindow.xml` is generated automatically and does not need to be copied during installation. apm only need to delete during uninstallation.
- fixes https://github.com/team-apm/apm/issues/1138
- Update of SplitWindow does not wipe the settings.
> fix: prevent overwriting of the config file

- v3/packages.json
Add an `authkey` so that the zip file can be downloaded without requiring a login. `authkey` is the one used by `https://aviutl.info/`.
- fixes https://github.com/team-apm/apm/issues/1188
- Open the URL and download the file.
> fix: use OneDrive without login

- v3/packages.json
In the latest version of DarkenWindow, `aviutl_dark.exe` and the installer have been deprecated, resulting in an un-installable state. I will fix this.
- The latest version of DarkenWindow can be installed and used.
- It's possible to update from DarkenWindow 7.3.0 and use it."
> fix: update DarkenWindow

- docs/install-script.html
- docs/main.css
- docs/package-sets-description.html
Replace bootstrap-dark-5 with the standard dark theme added from Bootstrap 5.3.
- Check the visibility of light and dark themes.
> feat: use bootstrap standard dark theme

- v3/packages.json
- `nazono/tlItemcut`の依存パッケージに、`nazono/patch`を追加
- The latest version can be installed and used.
`releases`に同じ内容の`5.0`と`v5.0`が存在するのは意図的でしょうか？
> fix: 切り取りプラグインの依存パッケージを修正

- v3/list.json
- v3/packages.json
Correct L-SMASH Works location. Also remove unnecessary integrity. 
- https://github.com/team-apm/apm/issues/1983
When `lwinput64.aui` is present, AviUtl freezes when opening the InputPipePlugin configuration screen without `InputPipeMain64.exe`. Therefore, add the `.exe` in this PR and increment the version so that the user is notified.
- fix https://github.com/team-apm/apm/issues/1983
After installation, the configuration screens for both plugins can be opened without problems.
> fix: change lsmashworks location
