team-apm/apm-data

data/packages_list.xml

Add all plugins from "AviUtl実験室" to the xml.

feat: add AviUtlLab packages

---

LICENSE
README.md

I'd like to add a license to this repository.
I'm thinking of adding CC BY-NC-SA 4.0 License.
What do you think?
Please give me your opinion.
I think one of the CC Licenses is good for this repository because it is dealing with data.

Add a license to this repository

---

data/packages_list.xml

fix: fixed broken packages

---

data/mod.xml

Update the modification time of xml.
#13 follow-up

update: mod.xml

---

data/mod.xml
data/packages_list.xml

Add all plugins from rigaya to the xml. 

feat: add rigaya packages

---

data/mod.xml
data/packages_list.xml

Add the rikky' rikky module and all the plugins of yunoimage.

feat: add yunoimage rikky packages

---

schema/packages_list.xsd

Add the dependencies element.
Close #18

feat(XML Schema): add the dependencies element

---

docs/install-script.html

Add an HTML file containing a link to the script. After publishing this file in Github Pages, it will be used by APM.
Check https://github.com/hal-shu-sato/apm/pull/142 for details.

feat: add HTML containing links to scripts

---

data/mod.xml
data/packages_list.xml

Add the dependencies tag to the XML.
closes #22 .

feat: add dependencies tags

---

docs/install-script.html

Add the author to the list of script authors. The authors will be listed in alphabetical order.

feat: add script author

---

yarn.lock

Update `prettier` and `prettier-plugin-md-nocjsp`.

build(deps): update some packages

---

package.json

Make HTML files lint in committing.

style(lint-staged): make HTML lint in committing

---

docs/install-script.html

- add Amazonish 
- change rikky's link
Amazonish (アマゾンっぽい) is a submission site, so scripts from multiple authors have been submitted.

feat: add Amazonish and change rikky's link

---

data/mod.xml
data/packages_list.xml

Fix dependency information. Required for https://github.com/hal-shu-sato/apm/pull/154 .

fix: dependency information

---

data/mod.xml
data/packages_list.xml

Add all plugins of karoterra.
- Load the file with apm and verify the displayed text and installation.

feat: add karoterra packages

---

README.en.md
README.md
data/mod.xml
data/packages_list.xml
schema/packages_list.xsd

Include the name of the author of the derived package in the xml. This PR is related to https://github.com/hal-shu-sato/apm/issues/174 .
- The current version of apm is able to read this xml correctly.

feat: clarify the original developers

---

docs/install-script.html
docs/main.css

Support for dark themes. `main.css` is an unmodified copy from the apm repository.
- https://github.com/hal-shu-sato/apm/pull/198

feat: support dark themes

---

data/mod.xml
data/packages_list.xml

Add descriptions to packages that do not have them.

fix: add descriptions

---

README.en.md
README.md
schema/packages_list.xsd

After adding the `continuous` attribute to `latestVersion`, update the Readme.
- https://github.com/hal-shu-sato/apm/pull/216

feat: add continuous attribute

---

data/mod.xml
data/packages_list.xml

Add multiple LSMASHWorks.
**This PR depends on the following PR(s).**
- https://github.com/hal-shu-sato/apm/pull/216
- #39
Closes #34
- Install and uninstall the package without any problems.

feat: add LSMASHWorks

---

.github/workflows/nodejs.yml

Change to run Node CI on pull requests.
I'll merge this PR soon.

ci(nodejs.yml): change to run Node CI on pull requests

---

data/mod.xml
data/packages_list.xml

Specify the dependencies using logical or.
- https://github.com/hal-shu-sato/apm/pull/217
- InputPipePlugin is not displayed as "⚠️インストール不可" even when VFRmaniacLSMASHWorks is installed.

feat: specify the dependencies using logical or

---

.github/dependabot.yml

Add a Dependabot setting file.
I'll merge this PR soon.

ci(Dependabot): add a Dependabot setting file

---

data/core.xml
data/mod.xml
schema/au.xsd

Remove the integrity attribute from data v1.
- #50

Revert integrity v1

---

v2/data/mod.xml
v2/data/packages.xml
v2/schema/packages.xsd

Change ID structure to `developer/package_name`.
Also, fix some typos.
- #50

feat: change ID structure

---

data/core.xml
data/mod.xml
data/packages_list.xml
schema/core.xsd
schema/mod.xsd
schema/packages_list.xsd

Add a `version` attribute to v1 files.
The app started successfully.

feat: add a version attribute on v1

---

data/mod.xml
data/packages_list.xml
v2/data/mod.xml
v2/data/packages.xml

- Change URLs of GitHub releases to the latest version.

fix: change URLs of GitHub releases

---

.github/workflows/check-update.yml
package.json
util/check-update.js
yarn.lock

Check version updates of packages that are released on GitHub.
- Check version update at 05:43 (JST) every day.
- Create a pull request if any updates are available.

ci(GitHub Actions): add automated update check

---

v2/data/mod.xml
v2/data/packages.xml

Adds integrity to some libraries.
- It works correctly in apm with https://github.com/hal-shu-sato/apm/pull/254 applied.

feat: add integrity to some libraries

---

.github/workflows/check-update.yml
util/check-update.js

- Fix time toString.
- Change the branch name to make.

Fix check update

---

README.en.md
README.md

Add contributors' names in README.
I'll merge this PR soon.

docs: add contributors in README

---

package.json
util/update-mod.js

Add a command to update the mod date.
I didn't come up with the idea except refresh the date ourselves.
- #60

util: add a command to update mod date

---

v2/data/mod.xml
v2/data/packages.xml

Add patch.aul and suzune's plugins.
The three packages can be installed by apm on the main branch.

feat: add patch.aul and suzune's plugins

---

.eslintignore
.eslintrc
package.json
util/sri.js
yarn.lock

Add a utility to generate a hash. (Similar to hal-shu-sato/apm, with a little improvement)

util: add a utility to generate a hash

---

v2/data/mod.xml
v2/data/packages.xml

Add images for transitions and the Maverick Tse plugins.
The packages can be installed by apm on the main branch.

feat: add transitions and Maverick Tse plugins

---

v2/data/mod.xml
v2/data/packages.xml

Add all plugins from rikky to the xml.
**This PR depends on the following PR(s).**
- #69
The packages can be installed by apm on the main branch.

feat: add rikky packages

---

v2/data/mod.xml
v2/data/packages.xml

Use https to increase the security of the communications.
You can install the packages as before.

fix: use https

---

v2/data/core.xml
v2/data/mod.xml
v2/data/packages.xml
v2/schema/core.xsd
v2/schema/packages.xsd

Supports the integrity of archives. This is used to validate the archive files.
- https://github.com/hal-shu-sato/apm/issues/235
- apm of the main branch can read this file normally (no change in behavior).

feat: add integrity to the archives

---

.github/workflows/codeql-analysis.yml
.github/workflows/nodejs.yml

- Add the `workflow_dispatch` trigger.
It allows us to run workflows manually.
I will merge this PR soon.

ci(GitHub Actions): add the `workflow_dispatch` trigger

---

package.json
util/update-mod.js
v2/data/mod.xml
v2/schema/mod.xsd

- Add the `convert.json` mod date.
- Add the `mod-convert` script.
- #50 
- hal-shu-sato/apm#281
apm on the main branch works correctly.

`convert.json` mod date

---

v2/data/mod.xml
v2/data/packages.xml

Relaxes oov/CacheText dependency.

fix: fix CacheText dependencies

---

v2/data/mod.xml
v2/data/packages.xml

Prevent apm freeze by changing the priority of packages that cause certificate errors.
- https://github.com/hal-shu-sato/apm/issues/343
- Confirmed that apm can read this file correctly.

fix: dependency priorities

---

v2/data/mod.xml
v2/data/packages.xml

Update the package data to the latest version. This will also fix the problem of x264guiEx failing to install.
- Confirmed that apm can successfully install and uninstall packages.

feat: update packages (Feb. 2022)

---

util/check-update.js

Remove the lines that are no longer needed due to the update of fast-xml-parser.

fix: fllow xml parser changes

---

README.en.md
README.md

Add karoterra to the Contributor section in README.
This PR will be merged soon.

docs: add karoterra in README

---

v2/data/mod.xml
v2/data/packages.xml

Update patch.aul version.
apm could install correctly.

feat: update patch.aul version

---

README.en.md
README.md

- Add a jsDelivr badge in README.
This PR will be merged soon.

docs(README): add a jsDelivr badge in README

---

v2/data/mod.xml
v2/data/packages.xml

Add Nure's and Nazono's package.
- closes #128
- closes #136
- Package will be installed correctly

feat: add nure, nazono plugins

---

.github/workflows/nodejs.yml

ci: using node 16

---

v3/data/packages.json
v3/schema/packages.json
v3/types/packages.d.ts

- merge `downloadURL` and `downloadMirrorURL` into `downloadURLs` as an array.
- #144

merge URLs into an array

---

v2/data/mod.xml
v2/data/packages.xml

Add MrOjii/LSMASHWorks to the recommended bulk installation packages.
- https://github.com/hal-shu-sato/apm/pull/432
- The above PR **MUST** be released before this data is merged.
- closes https://github.com/hal-shu-sato/apm-data/issues/87

feat: add directURL to MrOjii/LSMASHWorks

---

v2/data/mod.xml
v2/data/packages.xml

- Update Rigaya's packages.
- Support packages released on GitHub.

fix: update Rigaya's packages

---

v2/data/mod.xml
v2/data/packages.xml

Add a plugin by khsk.
- closes #179
- Confirmed that it can be successfully installed by the latest version of apm.

feat: add a khsk plugin

---

package.json
util/convert-2-3.js
util/sort.js
v3/core.json
v3/list.json
v3/packages.json
yarn.lock

Add nicommons IDs and utilities to convert v2 to v3 and sort JSON.
- Add `compare-versions`.
- Add a utility to convert from v2 to v3.
- Add a utility to sort JSON.
- Update and sort v3 files.
- Add a utility to detect nicommons IDs.
- Add nicommons IDs.
- team-apm/apm#271
- team-apm/apm#569
- team-apm/apm-data#122
- team-apm/apm#469
I haven't tested these data yet.

Add nicommons IDs

---

v2/data/mod.xml
v2/data/packages.xml
v3/list.json
v3/packages.json

Update the description of `localfont.aul`. Also, correct the download URL for `MrOjii/LSMASHWorks`.
- It can be read by apm in the main branch.

feat: update localfont.aul

---

.eslintrc
package.json
util/check-convert.js
util/check-update.js
util/convert-2-3.js
util/sort.js
util/sri.js
util/update-mod.js

util: change to use ESModules

---

.github/workflows/check-update.yml
package.json
util/convert-2-3.js
v3/list.json
v3/packages.json

- Add converting v2 to v3 in checking the update.
- Convert the latest v2 data to v3.
- Add the button to run check-update manually.

ci: add converting v2 to v3 in checking update

---

util/convert-2-3.js

- Change to output full paths for debugging.

util(convert-2-3): change to log full paths

---

util/convert-2-3.js

- Change to output paths on error.

util(convert-2-3): change to output paths on error

---

util/convert-2-3.js

- Add outputting paths on error.

util(convert-2-3): add outputting paths on error

---

util/convert-2-3.js

- Change the way to specify paths.
I think this will resolve the bug.

util(convert-2-3): change the way to specify paths

---

CONTRIBUTING.ja.md
CONTRIBUTING.md
README.en.md
README.md

- Change the repository owner in README and CONTRIBUTING

docs: change the repository owner in README and CONTRIBUTING

---

v2/data/mod.xml
v2/data/packages.xml
v3/list.json
v3/packages.json

- Update the direct URL of `MrOjii/LSMASHWorks`.

fix: update MrOjii/LSMASHWorks

---

v2/data/mod.xml
v2/data/packages.xml
v3/list.json
v3/packages.json

- Update the `directURL` of `MrOjii/LSMASHWorks`.

fix: update the directURL of MrOjii/LSMASHWorks

---

.github/workflows/check-update.yml

Ensure that the direct URL of L-SMASH Works is automatically updated.
- Tested on my shell only.

feat(check-update): update L-SMASH-Works

---

.github/workflows/check-update.yml
util/check-update.js

Fix a bug in #220 .
Ensure that the direct URL of L-SMASH Works is automatically updated.
- Test the behavior in the forked repository.

fix: updater for l-smash works

---

util/check-convert.js
util/check-update.js
util/sri.js
util/update-mod.js

- Reorder imports.
- Change to use async functions.
- Improve performance by processing parallelly.

Improve utilities

---

v2/data/mod.xml
v2/data/packages.xml
v3/list.json
v3/packages.json

Update hebiiro's plugins, including data for automatic installation of DarkenWindow.
- closes #232
- closes #233
- Installation can be performed normally.

feat: update hebiiro packages

---

.github/workflows/check-update.yml

- Change the owner of the 7-zip files before checking the update.

ci: change the owner of the 7-zip files before checking update

---

v2/data/mod.xml
v2/data/packages.xml
v3/list.json
v3/packages.json

Add or update audio-related plugins.
- Installation by release version apm is possible.

feat: update audio-related plugins

---

v2/data/mod.xml
v2/data/packages.xml
v3/list.json
v3/packages.json

Add hebiiro's UniteWindow plugin.
As this plugin does not work in my environment, I will remove the draft once I confirm that it works.
closes #247

feat: add UniteWindow

---

v2/data/mod.xml
v2/data/packages.xml
v3/list.json
v3/packages.json

- Add `textmodule` by `shummg`.
- close #251

feat: add shummg/textmodule

---

package.json
util/generate-releases.js

- Add a generator of releases.
I know there are bugs.
If you have any opinions, please let me know.

util: add a generator of releases

---

v2/data/mod.xml
v2/data/packages.xml
v2/data/scripts.json
v3/list.json
v3/packages.json
v3/scripts.json

Supports shummg's script distribution site.
~~This PR depends on shummg/textmodule which is not yet implemented.~~
- Each script on the script distribution site can be successfully installed.
- **"年月日カウンタ" does not work properly. I do not know why.**

feat: add shummg's site

---

v2/data/packages.xml
v3/packages.json

Add MaverickTse's AviUtlSvg.
- closes https://github.com/team-apm/apm-data/issues/253
- Verify that the script works.

feat: add AviUtl-svg

---

v2/data/packages.xml
v3/packages.json

Add the three plugins by ePi and the mtripg6666tdr's plugin. This PR is also a test to add a line break to the package description text.
- closes https://github.com/team-apm/apm-data/issues/255
- closes https://github.com/team-apm/apm-data/issues/256
- The packages can be installed successfully.

feat: add the ePi plugins

---

v2/data/mod.xml
v2/data/scripts.json
v3/list.json
v3/packages/tim.json
v3/scripts.json

Add the list of scripts by tim provided by @shumm7 . The reason for splitting the file is to reduce the size of the apm-data update.
Many thanks to Shu for providing so much package data.
- closes https://github.com/team-apm/apm-data/issues/257
- Visually check the package list on apm.

feat: add tim's scripts

---

util/archive-name-pattern.json
v2/data/mod.xml
v2/data/packages.xml
v3/list.json
v3/packages.json

feat: add hebiiro's SplitWindow

---

.release-it.json
package.json
yarn.lock

- Add `release-it` to support creating a tag.
I'll merge this PR soon.

build(deps-dev): add release-it

---

.release-it.json
package.json

- Change the config of `release-it`.

chore: change the config of release-it

---

util/generate-releases.js

- Increase the number of the limit of releases.

util: increase the number of the limit of releases

---

util/check-convert.js
util/check-update.js
util/generate-releases.js
util/lib/download.js
util/lib/generateHash.js
util/lib/unzip.js
util/sri.js
util/update-mod.js

- Update utilities for v3.
- #122

util: update utilities for v3

---

README.en.md
README.md

- Add the name of @glyzinieh in README.md.
- #325

docs(README): add a contributor's name

---

.github/workflows/check-update.yml

- Remove convert-2-3 from the check-update workflow.
- #311

ci(GitHub Actions): remove convert-2-3 from check-update

---

README.en.md
README.md
developer-id.md

- Add a document about Developer ID.

docs: add a document about Developer ID

---

v3/list.json
v3/packages.json

update: add a package

---

v3/list.json
v3/packages.json

Add the package data submitted by JI.
- closes #357
- closes #359 
- closes #374
- You can install and uninstall the packages with apm in the main branch.
- The installed packages will work on AviUtl.

feat: add packages by JI

---

v3/list.json
v3/packages.json

Add rikky's Dimensionize script. This script is referenced from `scripts.json` but is missing.
- You can install this script with apm in the main branch.

feat: add rikky's Dimensionize script

---

v3/list.json
v3/packages.json

Add the packages submitted by Infoengine1337.
Tasks
- closes #402 
- closes #403 
- closes #404 
- closes #405 
- closes #406 
- closes #407

feat: add the packages submitted by infoengine1337

---

.github/workflows/check-update.yml

Make the script that automatically updates Mr-Ojii's LSMASHWorks compatible with data v3.
None

ci(check-update): update mr-oji rev

---

v3/packages.json

This is a modification to make automatic updates work.

fix: update archivePath

---

package.json
util/format-json.js

- Add a JSON formatting tool.
- ID sort
- property sort

util: add a JSON formatting tool

---

v3/list.json
v3/packages.json

- Change to use HTTP for packages by AviUtlLab.
- Fix #458 
- Confirmed apm can open the pages and install AviUtlLab's packages.

fix: change to use http for packages by AviUtlLab

---

README.md

Update the list of contributors. The order of names is based on the date of first participation.

doc: update the list of contributors

---

developer-id.md
v3/packages.json

Add script by SEED264. Please check the operation of **DirectionalBlur_s** if possible. It did not work in my environment.
可能であればDirectionalBlur_sの動作確認をお願いします。
- closes #423 
- closes #434
- Script installs successfully.
- Script runs successfully.
- CUDA did not work in my environment, so `seed264/directionalblur` is untested.

feat: add seed264's script

---

v3/list.json
v3/packages.json

Update some packages data.
I temporarily changed `LANG=C yarn run check-update` to `yarn run check-update` to avoid the error of not being able to unzip the x264guiEx zip file and ran it.

[Update] Update packages data

---

v3/list.json
v3/packages.json

Add nazono's version of patch.aul.
- closes #490
- Installed and running successfully.

feat: add nazono's patch.aul

---

v3/list.json
v3/package-sets.json
v3/packages/tim.json

Add a link to the zip file to Tim's script. This reduces installation time. Also add 2 new Tim's scripts.
このデータは @shumm7 さんが投稿してくださいました。ありがとうございます！！！
- closes #527
- All scripts can be installed.

feat: add zip URL to tim's script

---

v3/packages.json

[アイテム内音声波形](https://github.com/hebiiro/AviUtl-Plugin-ShowWaveform/blob/master/README.md)に従って、以下の4点を変更しました。
- `patch.aul`は必須ではなく、あくまでも共存確認である。
- `L-SMASH Works`に依存する。
- `ShowWaveform.ini`は起動後生成される。インストール時に移動する必要はない。
- インストール時に`ShowWaveform`(フォルダ)を移動する必要がある。
- #580 
- #591 
- Successful installation by apm.
- The plugins runs on AviUtl.

feat: fix ShowWaveform

---

util/check-update.js

Fix check-update.js for new prettier 3.x.
- #629

util(check-update): fix for new prettier

---

v3/packages.json

- [Nagomikuさん](https://scrapbox.io/nanikani-shugo/Nagomiku%E8%87%AA%E4%BD%9C%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88)の「値で図形」スクリプトを追加しました。
- Nagomikuさんに開発者IDが振られていなかったため、`nagomiku`を使用しました。
- #598 
- Successful installation by apm.
- The script runs on AviUtl.

feat: add paracustomobj

---

v3/packages.json

Add 4 more packages, including a magnifying glass plugin.
- closes #491 
- closes #492 
- closes #510 
- closes #539
- Successful installation by apm in main branch.
- The plugins runs on AviUtl.

feat: add magnifying glass plugin, etc

---

util/convert-2-3.js
util/format-json.js
util/generate-releases.js
util/update-mod.js
v3/list.json

- Fix awaits for prettier v3.
- Update a mod date.
I confirmed each util works fine.

util: fix await for prettier v3

---

v3/packages.json

Updating the versions contained in the folder names.
- closes #597
- closes https://github.com/team-apm/apm/issues/765
- This was fixed in #323, but there is a regression caused by dfefb65 .
- You can successfully install these packages.

fix: update version in folder name

---

README.md
developer-id.md
v3/packages.json

Add multiple packages from the issues.
- closes #596 
- closes #611 
- closes #645
- closes #646
- closes #649 
- closes #651 
- closes #669 
- closes #671 
- closes #675
- All plugins and scripts can be installed and used.

feat: add multiple packages

---

package.json
yarn.lock

- bump dependencies
I will merge this PR soon.

build(deps): bump dependencies

---

package.json
yarn.lock

apm-schemaのバージョンを更新。最新のスキーマに基づいてCIが行われるようにする。
- #829 のCIを通すためのPRです。
`yarn`を実行するとapm-schema v3.3.0がダウンロードされました。
- ~~[ ] Updated the modification date in `mod.xml`.~~

build: update apm-schema

---

.github/dependabot.yml

- add a package pattern for the eslint group

build(dependabot): add a package pattern for the eslint group

---

v3/packages.json

- `hebiiro/UltimatePlugin`を追加
- `hebiiro/python32`を追加
- https://github.com/team-apm/apm-data/issues/694
- https://github.com/team-apm/apm-data/issues/703
- https://github.com/team-apm/apm-data/issues/735

feat: add hebiiro/ultimate plugin

---

docs/main.css
package.json
yarn.lock

build(deps-dev): bump dependencies

---

package.json
yarn.lock

build(deps-dev): bump @eslint/js and eslint to version 9.28.0, update prettier-plugin-packagejson to version 2.5.15
